In [1]:
import pandas as pd 
import numpy as np

In [2]:
# load database
url = 'https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv'
df = pd.read_csv(url)

🟢 Easy
Load the dataset and display the first 10 rows.
Find the total number of passengers (rows).
Check how many missing values exist in each column.
Find the average (mean) age of passengers.
Find the minimum and maximum Fare paid.
Count how many passengers survived vs. didn't (Survived value counts).
Count how many male vs. female passengers there were.
Find how many passengers were in each Pclass (1st, 2nd, 3rd).
Select only the Name, Age, and Survived columns into a new DataFrame.
Sort passengers by Fare, descending, and show the top 5.

In [ ]:
# Load the dataset and display the first 10 rows.
df.head(10)

In [ ]:
# Find the total number of passengers (rows).
len(df)

In [ ]:
# Check how many missing values exist in each column.
df.isnull().sum()

In [ ]:
# Find the average (mean) age of passengers.
df['Age'].mean()

In [ ]:
# Find the minimum and maximum Fare paid.
df['Fare'].min()
df['Fare'].max()

# row of max Fare paid
df.loc[df['Fare'] == df['Fare'].max()]

In [ ]:
# Count how many passengers survived vs. didn't (Survived value counts).
df['Survived'].value_counts()

In [ ]:
# Count how many male vs. female passengers there were.
df['Sex'].value_counts()
# for percantage and round
round(df['Sex'].value_counts(normalize=True) * 100,2)

In [ ]:
# Find how many passengers were in each Pclass (1st, 2nd, 3rd).
# sort index used second time for avoiding confisuon
class_df = pd.DataFrame(df['Pclass'].value_counts().sort_index())
class_df['Percentage'] = (df['Pclass'].value_counts(normalize=True) * 100).round(0).astype(int).astype(str) + '%'
                              
class_df

In [ ]:
# Select only the Name, Age, and Survived columns into a new DataFrame.
new_df = df[['Name','Age','Survived']].copy()
new_df

In [ ]:
# Sort passengers by Fare, descending, and show the top 5.
df.sort_values('Fare', ascending=False).head()

## Medium

🟡 Medium
Find the survival rate (%) by gender — group by Sex, mean of Survived.
Find the survival rate by Pclass.
Fill missing Age values with the median age.
Drop the Cabin column (too many missing values) — or count what % is missing first.
Create a new column FamilySize = SibSp + Parch + 1.
Create a new column IsAlone — 1 if FamilySize == 1, else 0.
Extract passenger titles (Mr, Mrs, Miss, etc.) from the Name column using string extraction.
Find the average Fare paid per Pclass.
Find the oldest and youngest survivor (full row, not just age).
Group by both Sex and Pclass, and find the survival rate for each combination.
Find how many passengers embarked from each port (Embarked), and which port had the highest survival rate.
Bucket Age into groups (e.g. Child: 0–12, Teen: 13–19, Adult: 20–59, Senior: 60+) using pd.cut, then find survival rate per age group.

In [ ]:
df.head()

In [ ]:
# Find the survival rate (%) by gender — group by Sex, mean of Survived.
df.groupby('Sex')['Survived'].mean()

In [ ]:
# Find the survival rate by Pclass.
df.groupby('Pclass')['Survived'].mean()

In [ ]:
# Fill missing Age values with the median age.
df['Age'] = df['Age'].fillna(df['Age'].median())

In [ ]:
# Drop the Cabin column (too many missing values) — or count what % is missing first.
null_cabin_percentage = df['Cabin'].isnull().sum() / len(df['Cabin']) * 100
null_cabin_percentage

# drop the cabin column
df.drop(columns='Cabin', inplace = True)
df

In [ ]:
# Create a new column FamilySize = SibSp + Parch + 1.
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df.head()

In [ ]:
# Create a new column IsAlone — 1 if FamilySize == 1, else 0.
df['IsAlone'] = np.where(df['FamilySize'] ==1, 1, 0)
df.head()

In [3]:
# Extract passenger titles (Mr, Mrs, Miss, etc.) from the Name column using string extraction.

df['Title'] = df['Name'].str.extract(r',\s*(\w+)\.')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr

In [8]:
# Find the average Fare paid per Pclass.
df.groupby('Pclass')['Fare'].agg(['mean', 'min', 'max', 'count'])

             mean  min       max  count
Pclass
1       84.154687  0.0  512.3292    216
2       20.662183  0.0   73.5000    184
3       13.675550  0.0   69.5500    491

In [24]:
# Find the oldest and youngest survivor (full row, not just age).
survivors = df[df['Survived'] == 1] 

oldest_survivor = survivors.loc[survivors['Age'].idxmax()]
youngest_survivor = survivors.loc[survivors['Age'].idxmin()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,Mrs
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,Mrs
...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C,NaN
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,Mrs
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,Mrs
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Mr

In [29]:
# Group by both Sex and Pclass, and find the survival rate for each combination.

df.groupby(['Sex','Pclass'])['Survived'].mean()

Sex     Pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.135447
Name: Survived, dtype: float64

In [48]:
# Find how many passengers embarked from each port (Embarked), and which port had the highest survival rate.
embarked_group = df.groupby('Embarked')['PassengerId'].size()
embarked_surv_rate = df.groupby('Embarked')['Survived'].mean().idxmax()
embarked_surv_rate

'C'

In [56]:
# Bucket Age into groups (e.g. Child: 0–12, Teen: 13–19, Adult: 20–59, Senior: 60+) using pd.cut, then find survival rate per age group.
age_bins = [0,12,19,59,100]
labels = ['Child','Teen','Adult','Senior']
# Apply pd.cut
categories = pd.cut(df['Age'], bins=age_bins, labels=labels)
df.groupby(categories)['Survived'].mean()

Age
Child     0.579710
Teen      0.410526
Adult     0.389313
Senior    0.269231
Name: Survived, dtype: float64