In [1]:
import pandas as pd

In [2]:
# load data
url = 'https://raw.githubusercontent.com/AnkitaSingh87/Netflix-Data-Project/main/Raw%20Data/netflix_titles.csv'
df = pd.read_csv(url)

Netflix Dataset — Practice Tasks
Find how many Movies vs TV Shows are in the dataset, and what percentage each makes up.
Find the average duration_minutes for Movies only (remember: TV Shows have NaN here, so you'll need to filter first).
Convert date_added to a proper datetime column, then extract just the year and month into two new columns.
Find how many titles were added to Netflix per year (using your new "year added" column, not release_year) — which year had the most additions?
Find the gap between release_year and the year it was date_added — create a new column years_to_netflix showing how many years after release the title was added. Which title had the longest gap?
Group by rating, and find the average duration_minutes per rating — do R-rated movies tend to run longer than TV-Y7 ones?
Find the most common rating overall, and separately, the most common rating for Movies vs for TV Shows.
Create a new column decade from release_year (e.g. 2019 → "2010s") using either pd.cut or a manual function, then find how many titles come from each decade.
Find all titles containing the word "Love" in the title column (string search), and show just title, type, and release_year for those matches.
Sort the dataset by duration_minutes descending and find the 5 longest movies — then do the same for duration_seasons to find the TV shows with the most seasons.
Handle the missing values properly: check .isnull().sum() for every column, then decide — should duration_minutes/duration_seasons NaNs be filled with 0, left as NaN, or is that even meaningful given they represent two different types of media?

In [3]:
# Find how many Movies vs TV Shows are in the dataset, and what percentage each makes up.
# drop one broken data
df = df[df['type'] != '1944']
(df.groupby('type').size() / len(df) * 100).round(2)

type
Movie      68.40
TV Show    31.58
dtype: float64

In [6]:
# Find the average duration_minutes for Movies only (remember: TV Shows have NaN here, so you'll need to filter first).

# duration minutes was kept as strings, converted to numeric
df['duration_minutes'] = pd.to_numeric(df['duration_minutes'], errors='coerce')

movie_df = df[df['type']=='Movie']
movie_df['duration_minutes'].mean()

np.float64(99.10082063305978)

In [8]:
# Convert date_added to a proper datetime column, then extract just the year and month into two new columns.

# I will drop release_year because I will add Year and month
df['date_added'] = pd.to_datetime(df['date_added'])
df['year'] = df['date_added'].dt.year
df['month'] = df['date_added'].dt.month

In [9]:
df.head(10)

,duration_minutes,duration_seasons,type,title,date_added,release_year,rating,description,show_id,year,month
0,90.0,NaN,Movie,Norm of the North: King Sized Adventure,2019-09-09,2019.0,TV-PG,Before planning an awesome wedding for his gra...,81145628.0,2019.0,9.0
1,94.0,NaN,Movie,Jandino: Whatever it Takes,2016-09-09,2016.0,TV-MA,Jandino Asporaat riffs on the challenges of ra...,80117401.0,2016.0,9.0
2,NaN,1,TV Show,Transformers Prime,2018-09-08,2013.0,TV-Y7-FV,"With the help of three human allies, the Autob...",70234439.0,2018.0,9.0
3,NaN,1,TV Show,Transformers: Robots in Disguise,2018-09-08,2016.0,TV-Y7,When a prison ship crash unleashes hundreds of...,80058654.0,2018.0,9.0
4,99.0,NaN,Movie,#realityhigh,2017-09-08,2017.0,TV-14,When nerdy high schooler Dani finally attracts...,80125979.0,2017.0,9.0
5,NaN,1,TV Show,Apaches,2017-09-08,2016.0,TV-MA,A young journalist is forced into a life of cr...,80163890.0,2017.0,9.0
6,110.0,NaN,Movie,Automata,2017-09-08,2014.0,R,"In a dystopian future, an insurance adjuster f...",70304989.0,2017.0,9.0
7,60.0,NaN,Movie,Fabrizio Copano: Solo pienso en mi,2017-09-08,2017.0,TV-MA,Fabrizio Copano takes audience participation t...,80164077.0,2017.0,9.0
8,NaN,1,TV Show,Fire Chasers,2017-09-08,2017.0,TV-MA,"As California's 2016 fire season rages, brave ...",80117902.0,2017.0,9.0
9,90.0,NaN,Movie,Good People,2017-09-08,2014.0,R,A struggling couple can't believe their luck w...,70304990.0,2017.0,9.0

In [10]:
# Find how many titles were added to Netflix per year — which year had the most additions?
df['year_added'] = pd.to_datetime(df['date_added'], errors='coerce').dt.year
df.groupby('year_added')['title'].count().sort_values(ascending=False)

year_added
2019.0    2349
2018.0    1782
2017.0    1299
2016.0     456
2020.0     184
2015.0      90
2014.0      25
2011.0      13
2013.0      12
2012.0       7
2008.0       2
2009.0       2
2010.0       1
Name: title, dtype: int64

In [11]:
# Find the gap between release_year and the year it was date_added — create a new column years_to_netflix showing
# how many years after release the title was added. Which title had the longest gap?

df['years_to_netflix'] = df['year_added'] - df['release_year']
# df['years_to_netflix'].sort_values(ascending=False)

# which movie is it
idx = df['years_to_netflix'].idxmax()

# you can add comma and type the columns you want
df.loc[idx]

duration_minutes                                                  NaN
duration_seasons                                                    1
type                                                          TV Show
title                               Pioneers: First Women Filmmakers*
date_added                                        2018-12-30 00:00:00
release_year                                                   1925.0
rating                                                          TV-PG
description         This collection restores films from women who ...
show_id                                                    81030762.0
year                                                           2018.0
month                                                            12.0
year_added                                                     2018.0
years_to_netflix                                                 93.0
Name: 4293, dtype: object

In [12]:
# Group by rating, and find the average duration_minutes per rating — do R-rated movies tend to run longer than TV-Y7 ones?
df['duration_minutes'] = pd.to_numeric(df['duration_minutes'], errors='coerce')

# searching in Movie dataset due to tv shows using duration_seasons instead of duration_minutes
movie_df = df[df['type']=='Movie']

rating_duration = movie_df.groupby('rating')['duration_minutes'].mean()
rating_duration['R'] > rating_duration['TV-Y7']

np.True_

In [13]:
# Find the most common rating overall, and separately, the most common rating for Movies vs for TV Shows.

# creating df instance for series
series_df = df[df['type']=='TV Show']

df.groupby('rating')['title'].count().idxmax()

movie_df.groupby('rating')['title'].count().idxmax()
series_df.groupby('rating')['title'].count().idxmax()   # TV shows only

'TV-MA'

In [14]:
# Create a new column decade from release_year (e.g. 2019 → "2010s") using either pd.cut or 
# a manual function, then find how many titles come from each decade.

bins = list(range(1920, 2031, 10))

# -1 because always one fewer range than there are edges.
labels = [f'{b}s' for b in bins[:-1]]
df['decade'] = pd.cut(df['release_year'], bins=bins, labels=labels, right=False)
df.groupby('decade')['title'].count().sort_values(ascending=False)

decade
2010s    5205
2000s     625
1990s     191
1980s      89
1970s      56
2020s      25
1960s      21
1940s      14
1950s       6
1920s       1
Name: title, dtype: int64

In [15]:
# Find all titles containing the word "Love" in the title column (string search), and show just title, type, and release_year for those matches.
title_love = df[df['title'].str.contains('love', case=False, na=False)]
title_love[['title', 'type', 'release_year']]

                                                 title     type  release_year
19                                                Love    Movie        2015.0
46                        Bangkok Traffic (Love) Story    Movie        2009.0
47                     I Fine... Thank You... Love You    Movie        2014.0
66    Christiane Amanpour: Sex & Love Around the World  TV Show        2018.0
74                                            Lovesick  TV Show        2014.0
...                                                ...      ...           ...
5850                  Ainori Love Wagon: Asian Journey  TV Show        2018.0
5898                                Roonpi Secret Love  TV Show        2016.0
5943                               My First First Love  TV Show        2019.0
6028                                          Lovesick  TV Show        2018.0
6050                                   Love Me As I Am  TV Show        2015.0

[135 rows x 3 columns]

In [20]:
# Sort the dataset by duration_minutes descending and find the 5 longest movies — 
# then do the same for duration_seasons to find the TV shows with the most seasons.

df['duration_seasons'] = pd.to_numeric(df['duration_seasons'], errors='coerce')
# filter out a tv show garbage season data
df = df[df['duration_seasons'] < 100]

df.sort_values('duration_minutes', ascending=False)[['title', 'duration_minutes']].head()
df.sort_values('duration_seasons', ascending=False)[['title', 'duration_seasons']].head()

                       title  duration_seasons
5910          Grey's Anatomy              15.0
5976                    NCIS              15.0
5789            Supernatural              14.0
6231            Red vs. Blue              13.0
6023  COMEDIANS of the world              13.0

In [21]:
# Handle the missing values properly: check .isnull().sum() for every column, then decide — 
# should duration_minutes/duration_seasons NaNs be filled
# with 0, left as NaN, or is that even meaningful given they represent two different types of media?
df.isnull().sum()

duration_minutes    1969
duration_seasons       0
type                   0
title                  0
date_added            10
release_year           0
rating                 2
description            0
show_id                0
year                  10
month                 10
year_added            10
years_to_netflix      10
decade                 0
dtype: int64