In [1]:
import pandas as pd

In [9]:
df = pd.read_excel('tips.xlsx')
df.head()

df.shape
#244 rows 9 columns

(244, 9)

In [11]:
# 1. Call our dataset and get its first 8 and last 4 rows, show number of observations
df.head(8)
df.tail(4)

        Name   Surname  total_bill   tip     sex smoker   day    time  size
240      NaN     Teece       27.18  2.00  Female    Yes   Sat  Dinner     2
241    Scott       NaN       22.67  2.00    Male    Yes   Sat  Dinner     2
242     Ajay     Munro       17.82  1.75    Male     No   Sat  Dinner     2
243  Tereasa  Duquette       18.78  3.00  Female     No  Thur  Dinner     2

In [38]:
# Report number of null values for each column. (3 points)
# a. Remove columns with null values. 

# df.isnull().sum()
df = df.dropna()

In [39]:
df.isnull().sum()

Name          0
Surname       0
total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [48]:
# What is the most frequent day of given tips? 
df.groupby('day')['tip'].count().sort_values(ascending=False).head(1)

day
Sat    73
Name: tip, dtype: int64

In [52]:
# Sort values by total bill and tip at restaurant in descending order. 
df_sorted = df.sort_values(['total_bill', 'tip'], ascending=False)
df_sorted.head()

          Name Surname  total_bill    tip   sex smoker  day    time  size
170  Stephanie   Foley       50.81  10.00  Male    Yes  Sat  Dinner     3
212       Jack    Ross       48.33   9.00  Male     No  Sat  Dinner     4
59        John   Yates       48.27   6.73  Male     No  Sat  Dinner     4
156      Tyson   Praed       48.17   5.00  Male     No  Sun  Dinner     6
182     Bertha   Siler       45.35   3.50  Male    Yes  Sun  Dinner     3

In [62]:
# Group by data by time and sex and find mean. (5 points)
# a. Which customers pay more than others?

result = df.groupby(['time', 'sex'])['tip'].mean()

In [66]:
# Filter total bill greater than 20 and tip less than 3
new_frame= df[(df['total_bill']>20) & (df['tip'] < 3)]
new_frame.sample(10)

          Name   Surname  total_bill   tip     sex smoker   day    time  size
208      Holly  Schroder       24.27  2.03    Male    Yes   Sat  Dinner     2
119       John    Hudson       24.08  2.92  Female     No  Thur   Lunch     4
57     Beverly      Bean       26.41  1.50  Female     No   Sat  Dinner     2
68       Ethan    Bolton       20.23  2.01    Male     No   Sat  Dinner     2
129     Archer       Ham       22.82  2.18    Male     No  Thur   Lunch     3
48      Andrew      Pugh       28.55  2.05    Male     No   Sun  Dinner     3
153  Christine     Dowdy       24.55  2.00    Male     No   Sun  Dinner     4
113      Molly     Iqbal       23.95  2.55    Male     No   Sun  Dinner     2
237      Julie  Faulkner       32.83  1.17    Male    Yes   Sat  Dinner     2
131       Kyle     Doyle       20.27  2.83  Female     No  Thur   Lunch     2

In [68]:
# Filter male customers with size equal to 2. 
male_filter = df[df['size'] == 2]
male_filter.sample(10)

,Name,Surname,total_bill,tip,sex,smoker,day,time,size
91,Scarlett,Webster,22.49,3.50,Male,No,Fri,Dinner,2
218,Harley,Hilton,7.74,1.44,Male,Yes,Sat,Dinner,2
15,Alex,McKenzie,21.58,3.92,Male,No,Sun,Dinner,2
68,Ethan,Bolton,20.23,2.01,Male,No,Sat,Dinner,2
113,Molly,Iqbal,23.95,2.55,Male,No,Sun,Dinner,2
133,Isabelle,Dalley-Scarlett,12.26,2.00,Female,No,Thur,Lunch,2
164,Annabelle,Williamson,17.51,3.00,Female,Yes,Sun,Dinner,2
109,Caden,McLean,14.31,4.00,Female,Yes,Sat,Dinner,2
81,Anna,Ryrie,16.66,3.40,Male,No,Thur,Lunch,2
97,John,Jones,12.03,1.50,Male,Yes,Fri,Dinner,2

In [72]:
# Find most frequent gender using “if” function.
male_count = (df['sex'] == 'Male').sum()
female_count = (df['sex'] == 'Female').sum()

if male_count > female_count:
    print('Male')
elif female_count > male_count:
    print('Female')
else:
    print('Tie')

Male

In [77]:
# Find number of bills greater than daily average. 
avg_bill = df['total_bill'].mean() 
# Count bills greater than average
count_above_average = (df['total_bill'] > avg_bill).sum()
count_above_average

np.int64(79)